CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:7N91VfMjsXsNOk5hi8W/ClaOj0s50hd23W50F04vyV2SNx8Ydc+3yS+eESexApNIeXnlvcI=,iv:WrRElr5E6lk5GvLIKj6ZexcTfUMxh64uWYvaqYiKmR0=,tag:jnDL4yTGvm3GtW5eCoOqhw==,type:str]
WEB_TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:hmV0PjY6EjRw7iFHhUq67qN5Qa4l1FcGbDNI+Dm45N2+i43hbiXLk3VfMtLEMg==,iv:zfaWO4r1oXaTXehVHvCI525N95yP57YAPLHLkRT5Cs0=,tag:aNhgVXzflMu2UwbFQ4bD7w==,type:str]
sops:
    age:
        - recipient: age1cq0k9s88fmx7kkaqqvuf290lelyt8gkeglwvsd2r3ezuqyla7aps7x4q2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSzZOOEtuSStxc29jUE1D
            cTdtUVRyV3AvS2xzb3RWekZYTFlzeDNOUVc4Ck80RnE2bHc0bnp5YjR6WFQ0eXVH
            OWx2UFgvV1cvNHpzM2lmbFlkc2htUVEKLS0tIFN1alZKZmk5cVUwM0RCU2pzUk5R
            SEU4VGtGUll4dEd0V3R6aks5SkM5dGsKDa3t3XS+SM6l1FZ5oyXV58ixGAv+zXOD
            cSrbZzfzaX8H/mmT67ZMs0BN/5YJhHMLuDbbu3KflSZtvujd9MxXCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-04T01:27:58Z"
    mac: ENC[AES256_GCM,data:WVGYeZ6elIZP9V92Wnw9Pds6yMNe+iiWPXGgggRiIri83UOa3gkSBILkeBRvRYAg3WSqlmjphIWqRskfpWKp2/XaVZfjC5etvJlRXA7onUH+i8eIGsP4+dpw3KqG6bx1i3QUkv/9qJzGhMosqKJSXCaaIBq4zfEJA88eSijLWP8=,iv:8a2vrZq3IRe5pQxV1rxd5EJqDvnJH8+kobqikuyuabU=,tag:jBlhhFf8JTUEV+0abwIUfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
