CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:7N91VfMjsXsNOk5hi8W/ClaOj0s50hd23W50F04vyV2SNx8Ydc+3yS+eESexApNIeXnlvcI=,iv:WrRElr5E6lk5GvLIKj6ZexcTfUMxh64uWYvaqYiKmR0=,tag:jnDL4yTGvm3GtW5eCoOqhw==,type:str]
sops:
    age:
        - recipient: age1cq0k9s88fmx7kkaqqvuf290lelyt8gkeglwvsd2r3ezuqyla7aps7x4q2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSzZOOEtuSStxc29jUE1D
            cTdtUVRyV3AvS2xzb3RWekZYTFlzeDNOUVc4Ck80RnE2bHc0bnp5YjR6WFQ0eXVH
            OWx2UFgvV1cvNHpzM2lmbFlkc2htUVEKLS0tIFN1alZKZmk5cVUwM0RCU2pzUk5R
            SEU4VGtGUll4dEd0V3R6aks5SkM5dGsKDa3t3XS+SM6l1FZ5oyXV58ixGAv+zXOD
            cSrbZzfzaX8H/mmT67ZMs0BN/5YJhHMLuDbbu3KflSZtvujd9MxXCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T16:52:32Z"
    mac: ENC[AES256_GCM,data:5kPVYCDoPZIJxztURXmARGFsMjEA8sEXnGtcncGvLmcLu4GODWLp4Y9AVYDpE1o0atK0u7kZFWZ+r7uSMLtzPve7XHkQGGULNAKhqfAIAXGFxaMzQuDYSq9cn6hMRR9+hjfnHnwqIKTAyHpEBgxGyi5thuiARwgfo+Kaq9jK5ok=,iv:0e5igyrbavxnuZJz8eg2lq2rkcuG5L084FBPKL5JsyU=,tag:3Zv9B1Yy4mEhqjEBGxmUuQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
